### ISSUE TITLE
no such file to load -- rubycocoa (LoadError)

### ISSUE THREAD

**Issue by scriptfans** [mockko/livereload#22] opened 2010-08-10 13:37 UTC
snow leopard 10.6.4 + ruby 1.8.7——

scriptfansmatoMacBook-Pro:untrip html scriptfans$ livereload

Version:  1.4  (compatible with browser extension versions 1.4.x)
Port:     35729
Watching: /Users/scriptfans/untrip html
- extensions: .html .css .js .png .gif .jpg .php .php5 .py .rb .erb
- excluding changes in: _/.git/_ _/.svn/_ _/.hg/_
- with a grace period of 0.05 sec after each change

LiveReload is waiting for browser to connect.
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- rubycocoa (LoadError)

How to solve this problem？

**Comment by NV** [comment] 2010-08-10 20:30
Do you have [RubyCocoa](http://rubycocoa.sourceforge.net/HomePage) installed?

History repeats itself. XRefresh had a lot of troubles with RubyCocoa http://github.com/darwin/xrefresh/issues#issue/10

**Comment by andreyvit** [comment] 2010-08-10 22:50
While this is a duplicate of a duplicate of a duplicate, I'm still marking this as help-wanted. We did 90% of the work needed to get FSEvents working without Ruby Cocoa. C'mon guys, somebody can do the remaining 10% while we're focusing on our startup which we've built LiveReload for in the first place. :)

**Comment by thibaudgg** [comment] 2010-08-11 08:24
You can look how I handle FSEvents without RubyCocoa inside RSpactor 0.7 http://github.com/thibaudgg/rspactor

**Comment by andreyvit** [comment] 2010-08-11 09:16
@thibaudgg Great, definitely will.

**Comment by scriptfans** [comment] 2010-08-11 15:33
@thibaudgg
how to do it? I try to:
gem install rspactor
but livereload still not working:(
sorry for my english, I am a chinese，macos newbie.

**Comment by thibaudgg** [comment] 2010-08-11 18:47
@scriptfans, At the moment RSpactor only handle changes for RSpec not livereload sorry. RSpactor is here given as an example to how handle system files event without RubyCocoa. Seems more clear for you now?

**Comment by scriptfans** [comment] 2010-08-11 23:28
@thibaudgg, understand，thank you very much!

**Comment by dottedmag** [comment] 2010-08-17 05:41
I am closing this issue as duplicate to newly created umbrella #24 (get rid of RubyCocoa).

**Closed as completed by dottedmag** 2010-08-17 05:41 UTC
Labels: planned
